services:
  postgresdb:
    container_name: postgresdb
    image: postgres:14-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USER=postgres_user
      - POSTGRES_DB=test

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=postgresdb